# ============================================== 基本配置开始
# 数据源配置
cyz: gogogogogo----from prod
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/imp_data?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root

# 日志路径
logging:
    path: /var/tmp/base-example

# sql 日志 需要的时候再开启
#   level:
#     com.potatoimp.dao: debug

# MyBatis
mybatis:
    type-aliases-package: com.base.object.po
    mapper-locations: classpath:/mybatis/*.xml
# mapper
mapper:
    mappers:
        - com.base.business.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
# pagehelper 分页插件配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql


# ============================================== 基本配置结束

# ============================================== 自定义配置开始


# ============================================== 自定义配置结束
